### ISSUE TITLE
add NeuroDebian?

### ISSUE THREAD

**Issue by bcdarwin** [repology/repology-updater#1019]
http://neuro.debian.net/pkgs.html

**Comment by AMDmi3** [comment]
Is it used, is it maintained? Looks small and severely outdated.

**Comment by AMDmi3** [comment]
I'd like a minimal explanation instead of silent close please. If you suggest to add it just because it exists, that's not good enough reason, especially that it includes a lot of repositories for different Debian and Ubuntu versions. If you use or maintain it, and would benefit of informatin of outdated versions, it's worth the effort.

**Comment by bcdarwin** [comment]
I agree that it is somewhat small and some packages are outdated.  However, this isn't uniformly true:  I looked at a couple popular packages: [nibabel](http://neuro.debian.net/pkgs/python3-nibabel.html) and [dcmstack](http://neuro.debian.net/pkgs/python3-dcmstack.html).  Nibabel is behind the current release but ahead of Debian (non-unstable) repos, and `dcmstack` is up-to-date.  Additionally, many of the developers of these projects are NeuroDebian users (see https://twitter.com/NeuroDebian) and therefore repology could be used to track new versions of some (but obviously not all) packages.  Finally, since a number of people use the NeuroDebian VM for reproducible research, this package set could serve as a baseline for neuroimaging packages for other repositories.  [I maintain a number of neuro- and ML-related packages in NixPkgs.]

Of course, it's your decision as to whether this is worthwhile.

**Comment by AMDmi3** [comment]
Thanks, now this makes sense. Will deploy it tomorrow.
