### ISSUE TITLE
buildroot

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#1081]
Embedded linux project with own packages

https://git.busybox.net/buildroot/tree/package/cmake/cmake.mk

No usable index, just .mk files.

**Comment by bkuhls** [comment]
Just came across your project and would like to point out these URLs which should work as index:
JSON: http://autobuild.buildroot.net/stats/master.json
HTML: http://autobuild.buildroot.net/stats/master.html

**Comment by qweered** [comment]
Up again https://gitlab.com/buildroot.org/buildroot

**Comment by AMDmi3** [comment]
It still returns HTML instead of json (probably anubis issue)

```
Oct 06 15:47:26   ERROR: failed: YAJL error: lexical error: invalid char in json text.
                                       <!doctype html><html lang="en">
                     (right here) ------^
```

**Comment by jolivain** [comment]
I confirm this was most likely an Anubis error. I think this is because repology was using the http URL, and Anubis is always rejecting http by default. See COOKIE_SECURE in: https://anubis.techaro.lol/docs/admin/installation/

Would it be possible to retry with the following https URLs?

Package stats from:
https://autobuild.buildroot.org/stats/

The most important branch to track is "master":
https://autobuild.buildroot.org/stats/master.json

Then, eventually, the 2025.02.x branch, which is a 3 year LTS version:
https://autobuild.buildroot.org/stats/2025.02.x.json
The next expected LTS will be 2027.02.x. See:
https://buildroot.org/lts.html

I don't think it is worth tracking intermediate non-LTS (3 months support) releases, or the "next" branch which is used during the release client cycles.

Buildroot git repository is now on hosted on gitlab:
https://gitlab.com/buildroot.org/buildroot.git

It would be really nice to have Buildroot back in repology. Thanks!

**Comment by AMDmi3** [comment]
I don't plan to work on this, PRs are welcome.
