### ISSUE TITLE
Request Arch Linux POWER repositories

### ISSUE THREAD

**Issue by QuarkTheAwesome** [repology/repology-updater#1227]
Not my project, but it's a port of Arch for powerpc{,64le}, and apparently riscv64.

https://archlinuxpower.org/
https://repo.archlinuxpower.org/base/
https://repo.archlinuxpower.org/testing/

Would be good to compare with Arch base.
Thanks!

**Comment by AMDmi3** [comment]
Added, but I'm thinking of undoing it. I've expected it to be close to arch repo, maybe with some additional patches, but it does seem to contain versions not present in arch and I cannot find a source of these.

For example, it claims to contain latest version of [spidermonkey](https://repology.org/project/spidermonkey/versions) but it's not even present in its github [repo](https://github.com/kth5/archpower).

In fact, new repositories are required to provide links to package sources (or it should be possible to generate such links e.g. out of package names), but it's also not possible for Arch POWER.

@kth5 ping, any comments? Where does spidermonkey 95.0 come from?

**Comment by AMDmi3** [comment]
@kth5 With all due respect, your consent is not required, and your users have right to know the coverage, outdatedness and vulnerability statistics of your repo.

**Comment by kth5** [comment]
@AMDmi3 As I duly noted, it is a preference since I - at least for the time of writing - am not able to provide the capacities required to keep all packages are up to date with versions and vulnerabilities. It is a personal project of mine and am the sole contributor.

All that said, I appreciate issues being reported on the project itself and am open for contributions of course.

**Comment by AMDmi3** [comment]
@kth5 I'm in a slightest way implying that you are obliged to spend more time on the project or chase after improving the numbers. That's not what repology is about. I'm just saying that making the information public benefits everybody - your users since they know whether they can use the repository for their tasks and what they should pay attention to; you, as you know where to improve; maintainers from other repositories since they can look up how ppc/riscv problems are already solved by you; upstream, which will get the state of their software on another set of architectures, and will probably merge related fixes.
