### ISSUE TITLE
Add build logs for Fedora/EPEL packages

### ISSUE THREAD

**Issue by robert-scheck** [repology/repology-updater#1274]
Right now, there are no build logs for Fedora/EPEL packages at Repology. These exist however using the following scheme:

```
https://kojipkgs.fedoraproject.org/packages/<source package>/<version>/<release>/data/logs/<architecture>/build.log
```

Not sure how architecture could be handled at Repology properly (x86_64 isn't the ultimate answer due to noarch packages), maybe it makes sense to simply avoid the last two URL chunks when linking (and let users finally navigate using the directory index).

The name, version, release can be extracted from the source RPM using RPM techniques, or even simply from the source RPM file name, when removing `.src.rpm` first, then walking backwards through the filename and splitting on `-` three times. Doing this from the front won't work, as the name could contain `-`, too (e.g. php vs. php-pear-something).

**Comment by AMDmi3** [comment]
> Not sure how architecture could be handled at Repology properly (x86_64 isn't the ultimate answer due to noarch packages)

We already have a field to store package architecture, however it was not filled because it was not used anywhere. It's time to enable it as we already need it for Arch for the similar purpose:

https://github.com/repology/repology-updater/blob/d016fdadc55231d8cafde6486aede608b17be135/repos.d/arch/arch.yaml#L27

However unfortunately for this case, we only parse source packages for Fedora/EPEL, so `arch` for them equals `src` which is useless for the case.

> maybe it makes sense to simply avoid the last two URL chunks when linking (and let users finally navigate using the directory index).

Yes, I guess we'll have to introduce distinctive link type for build log directory (as opposed to build log itself) and add it for Fedora/EPEL.
