### ISSUE TITLE
Switch OpenBSD to sqlports

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#149]
https://ftp.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/sqlports-6.0.tgz -> parse with sqlite

**Comment by landryb** [comment]
Parsing the INDEX in cvs is *definitely* not the right way to get accurate versioning, as it is only updated manually from time to time, cf https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/INDEX

An example: right now https://repology.org/metapackage/firefox/versions shows that openbsd ships 62.0.3 (which is misleading information..) while openports.se and cvsweb show that the port has been updated to 63.0.1 a week ago... and the same is true for many pkgs.

**Comment by AMDmi3** [comment]
sqlports has its downsides too which makes me hesitant about switching to it right away
- it's architecture-tied (though INDEX may be too)
- it's tied to OpenBSD version, which results in fetch breaking with each OpenBSD release
- it requires additional dependency for parsing

**Comment by landryb** [comment]
INDEX is arch-dependent too of course. And yes, the sql model changes from times to times, but not that often... when the model changes, the version number is bumped so you know when this happens.

**Comment by marcespie** [comment]
I just cobbled together an sql script that's part of sqlports...
you'll now get something mostly identical (actually improved as it's the closure of all pkgpaths) in the portslist package, starting at portslist-6.10.

THAT specific information should be arch-independent. You will still have to fix things so that it gets stuff from the right directory (snapshots/amd64 ?) and unpack it yourself.

But it's guaranteed to be updated each time a new snapshot is released.

The sql might evolve depending on how you parse things...   I might eventually have a "better" version, because you know it's fairly trivial to get a LOT of stuff from ftp...

**Comment by marcespie** [comment]
like landry said, both INDEX and sqlports are somewhat arch-dependent. Namely, INDEX is regenerated on some architecture, and there is nothing outside of coding style that prevents it from changing from arch to arch, even though that's discouraged.

Likewise, sqlports will contain so much more information that some of it is definitely arch-dependent... but the part you need for INDEX-like processing should be arch-dependent.

Note that INDEX has been built on amd64 for ages, actually... that is whenever someones remembers to commit it.

I can guarantee that the new sqlports-based file will be kept waaaay more uptodate.

**Comment by AMDmi3** [comment]
I've just finished new OpenBSD parser code which parses sqlports, can switch to it after some testing.
It has some improvements over INDEX-based one, for instance it supports parsing port downloads (e.g. `distfiles` including `{}` and `:N` handling and `master_sites*`). Not sure if switching back to clumsy CSV is needed any more. However, I'd really prefer switching to something which is easier to parse and more extensible then these both (e.g. JSON), does not require extra steps to fetch/parse (e.g. unpacking a .tgz) and does not require updating an url (e.g. the version). That is, a JSON dump put into some fixed location, probably outside the package directory.

I assume you guys are related to OpenBSD ports, so I also have some questions to ask. The most important bits of package data for Repology are project names and versions. The former are by default taken from package names, but the catch here is that package names must be neither ambiguous (e.g. when a single name may correspond to multiple unrelated projects) nor altered (e.g. by adding individual suffixes). Coping by violations of these rules require writing and maintaining a lot of rules, and must be avoided at all cost.

Most repositories use prefixes (py-, py3- p5-, ruby- etc.) for module packages, which mostly fixes the first problem. The second problem is only actual when repositories use subpackages or package variants, but most provide a name of _base_ or _source_ package which is named by the project name without modifications in most cases.

It's pretty complex for OpenBSD though. Here are some relevant examples (`PROJECT` is that I'd like to extract; `CANONICAL` and `PKGPATH` come from `Paths` table joined with `Ports` by `FULLPKGPATH`)

| PROJECT        | FULLPKGPATH                       | FULLPKGNAME                  | PKGNAME          | PKGSTEM      | PKGSPEC        | CANONICAL                         | PKGPATH                        | 
|----------------|-----------------------------------|------------------------------|------------------|--------------|----------------|-----------------------------------|--------------------------------| 
| luaposix       | devel/luaposix                    | luaposix-33.4.0p1v0          | luaposix-33.4.0  | luaposix     | luaposix-*     | devel/luaposix                    | devel/luaposix                 | 
| luaposix       | devel/luaposix,lua52            | lua52posix-33.4.0p1v0        | luaposix-33.4.0  | lua52posix   | lua52posix-*   | devel/luaposix,lua52            | devel/luaposix                 |   
| luaposix       | devel/luaposix,lua53            | lua53posix-33.4.0p1v0        | luaposix-33.4.0  | lua53posix   | lua53posix-*   | devel/luaposix,lua53            | devel/luaposix                 |   
| fftw3          | math/fftw3,-common              | fftw3-common-3.3.7           |                  | fftw3-common | fftw3-common-* | math/fftw3,-common              | math/fftw3                     |   
| fftw3          | math/fftw3,-main                | fftw3-3.3.7                  |                  | fftw3        | fftw3-*        | math/fftw3,-main                | math/fftw3                     |   
| fftw3          | math/fftw3,float,-common        | fftw3-common-3.3.7           |                  | fftw3-common | fftw3-common-* | math/fftw3,float,-common        | math/fftw3                     |   
| fftw3          | math/fftw3,float,-main          | fftw3-float-3.3.7            |                  | fftw3-float  | fftw3-float-*  | math/fftw3,float,-main          | math/fftw3                     |   
| mpegtools      | multimedia/mjpegtools             | mjpegtools-2.0.0p9           | mjpegtools-2.0.0 | mjpegtools   | mjpegtools-*   | multimedia/mjpegtools             | multimedia/mjpegtools          | 
| mpegtools      | multimedia/mjpegtools,quicktime | mjpegtools-2.0.0p9-quicktime | mjpegtools-2.0.0 | mjpegtools   | mjpegtools-*   | multimedia/mjpegtools,quicktime | multimedia/mjpegtools          |   
| gkrellflynn    | sysutils/gkrellm/plugins/flynn    | gkrellflynn-0.8p9            | gkrellflynn-0.8  | gkrellflynn  | gkrellflynn-*  | sysutils/gkrellm/plugins/flynn    | sysutils/gkrellm/plugins/flynn | 
| (python) jinja2 | www/py-jinja2                     | py-jinja2-2.10               | py-jinja2-2.10   | py-jinja2    | py-jinja2-*    | www/py-jinja2                     | www/py-jinja2                  | 
| (python) jinja2 | www/py-jinja2,python3           | py3-jinja2-2.10              | py-jinja2-2.10   | py3-jinja2   | py3-jinja2-*   | www/py-jinja2,python3           | www/py-jinja2                  

What I currently do is
- take `FULLPKGNAME`
- strip `-[a-z_]+[0-9]*` variant suffixes from it
- strip epoch and revision
- split package name and version

INDEX provided no variants as it basically only contained `FULLPKGPATH` and `FULLPKGNAME` in sqlports terms. sqlports provide more data, however there are still no directly usable bits as I hoped there will be (e.g. no separate version and package name columns). Still there's more to choose from and `PKGNAME` seem most interesting for now, however what worries me is that it is not defined for all packages.

So could you please elaborate where `PKGNAME` comes from, why's it different from other columns, why is it not defined for all ports and maybe share some thoughts on what can be improved here in OpenBSD parsing.

**Comment by marcespie** [comment]
PKGNAME defaults to DISTNAME, actually.  But it doesn't have to be defined for multi-flavored packages, which is what you see here, like math/fftw3  doesn't bother defining it for actual packages, it goes straight to FULLPKGNAME.

Ports itself doesn't really care about separating version numbers.
The only case where it cares if for checking with new version, and then you look at PORTROACH annotations for that.

The way package names are defined goes backward to what you're doing.
Refer to

https://man.openbsd.org/packages-specs

Specifically, you should identify the beginning of the version number first, then you can easily strip flavor markers. and get rid of revision/epoch.

.e.g., you've got PKGSTEM in sqlports that contains exactly the stem of the package with everything removed, including version and flavors.

Note that we maintain ascending version numbers. So sometimes, they do not quite match upstream.

Maybe you want to look at distfiles instead ? I don't quite know what you're doing.


We have no intention of changing package naming nor adding supplementary annotations to ports.  What we have suits our needs...

**Comment by AMDmi3** [comment]
> Refer to https://man.openbsd.org/packages-specs

Thanks for clarification. It looks like I'm doing this correctly.

> Note that we maintain ascending version numbers. So sometimes, they do not quite match upstream.

I've though you have epochs for this.

> Maybe you want to look at distfiles instead ?

This is tempting, but may hinder consistency. It's worth investigating on the global scale though.

> We have no intention of changing package naming nor adding supplementary annotations to ports. What we have suits our needs...

I've had a glimpse that you're interested in improving OpenBSD support in repology.

Well the support for sqlports is committed, but it broke right away because version was bumped. I don't think I want to chase a moving target, so I'm staying on INDEX for now. It may be outdated, but at least it doesn't break sporadically and require constant maintenance.

**Comment by marcespie** [comment]
Well, the version number of sqlports is going to move *all the time*.

Basically, it changes about every time we tweak the database schema, because variables get added, tables get improved.

If your scheme breaks because you cannot manage to say "list the files on this server, get the one that matches portslist-*.tgz, and unpack it", I'd say it's the part that needs to get fixed.

**Comment by marcespie** [comment]
oh, and you have to move forward, with parsing sqlports proper.

I'm currently fiddling with sqlports, because INDEX is going to go away, for good, because it's broken.

INDEX is lagging all the time.

current log for 2018 says: 2018/10/10, 2018/09/20, 2018/07/19, 2018/05/12, 2018/03/26, 2018/02/19.

That's about one update every two months... unlikely to get more frequent.

**Comment by AMDmi3** [comment]
> If your scheme breaks because you cannot manage to say "list the files on this server, get the one that matches portslist-*.tgz, and unpack it", I'd say it's the part that needs to get fixed.

All currently supported 200+ repositories are fetched by known constant urls. I will not implement complex file listing parsing logic for a single repository which does not care of publishing package metadata properly. Sqlite based parser is already too much on its own.

**Comment by marcespie** [comment]
the sqlports data has been crafted precisely so that any third party can process it and create that information.

I guess the best way to get that is to create the vacuum.

In the past, people (not only you but others) have been sloppy and have relied on INDEX, which is partial, and woefully unaccurate.

Removing that file will most probably  incite some people with time on their hands to give you what you suggest.

Better to have no information than wrong information.

Lots of these 200+ repositories are maintained by various people.  You say you can't be bothered to create code that does publish package metadata.  Neither can I. Or rather it is incredibly low on my very very very long list of things to do.

**Comment by AMDmi3** [comment]
I don't have much complaints on the dump format. It could be better, but it's not the worst and the parser is pretty simple. And already written. My main complaint is on the way the dump is distributed, where one need to perform a lot of complex actions such as getting a file listing, parsing it (and I'll remind that it's HTML which is of different structure on each mirror), finding a file to download then unpacking it and getting rid of unneeded files. The requirement for this is completely unjustified and basically nullifies the usefulness of the dump to third parties.

>  You say you can't be bothered to create code that does publish package metadata. Neither can I

It's senseless to compare effort needed once to write a code to publish a single file in a fixed location on the CDN and an effort needed from every consumer to write complex and fragile logic described above.

**Comment by AMDmi3** [comment]
There's nothing more to do here. The code for sqlports support is there, but it can't be used because the file location changes constantly.

**Comment by landryb** [comment]
Do you realize that by doing so, you decided to show information from a past/fixed date for OpenBSD, never refreshing the data ? That will send such a wrong message to users consulting repology, thinking OpenBSD only ships outdated software.......

**Comment by AMDmi3** [comment]
That's the best I can do in the current situation.

**Comment by marcespie** [comment]
> That's the best I can do in the current situation.

No, that's the best **you're willing to do** in the current situation.

**Comment by AMDmi3** [comment]
I've already stated what's needed for proper OpenBSD support. The requirement is very, very simple - a stable file location. Not only it still is not available, but you've deliberately broken alternative, working data source. So if you want to put it that way, I do the best you let me to do.

**Comment by landryb** [comment]
Having a stable file location under an *.openbsd.org domain is probably out of the question, as that would mean involving ppl to setup something in an infrastructure which is already doing a lot.

Having it in the pkg set unpacked automatically would mean adding something to the process used to generate packages, which is already complicated (and involves other ppl)

So i went for the middleground solution, since we control ftp.fr i've added a script to our mirrors update process to unpack INDEX from portslist package. It is in no way official, but the url should be stable: http://ftp.fr.openbsd.org/pub/ports-INDEX

Now, can we please get accurate information about versions shipped by openbsd, instead of deliberately misleading info ? thanks ! :)

**Comment by AMDmi3** [comment]
@landryb 

```
% curl -I http://ftp.fr.openbsd.org/pub/ports-INDEX 
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 0  <======
Content-Type: application/octet-stream
Date: Wed, 17 Jul 2019 16:28:46 GMT
Last-Modified: Wed, 17 Jul 2019 01:11:43 GMT
Server: OpenBSD httpd
```

**Comment by landryb** [comment]
@marcespie: indeed ports-INDEX seems empty in latest portslist-7.24:
```
 0 Jul 15 02:17 /usr/local/share/ports-INDEX
```

**Comment by landryb** [comment]
Thanks, it finally works, as can be seen on https://repology.org/repository/openbsd

**Comment by fingolfin** [comment]
Sorry for beating dead (?) horse, but I just saw the warning message on https://repology.org/repository/openbsd which indicates that lack of package homepage information might result in OpenBSD being removed from Repology, which would be a shame, IMO (and I am not even an OpenBSD user ;-).

This leads me to a naive question: Since @landryb already generously adjust the mirror scripts for ftp.fr.openbsd.org to create http://ftp.fr.openbsd.org/pub/ports-INDEX, I am now wondering: Would it perhaps also be possible with moderate (?! of course easy to say if one doesn't have to do the work) effort to change those mirror scripts to create a symlink from `pub/OpenBSD/snapshots/packages/amd64/sqlports-*.tgz` to, say `pub/sqlports.tgz` ?  If I understand things right, this would then allow @AMDmi3 to use that as fixed URL for the sqlports. And that then would give the desired homepage metadata, and more.

Of course doing this relies on @landryb generously spending his limited time on this, so i am not expecting anything; just wanted to bring it up in case the required setup is so that it would be easy to do for him (which I obviously cannot judge)

**Comment by AMDmi3** [comment]
Yes, it would solve the problem. I was wondering why it wasn't the solution from the start as it would seem much simpler and faster than generating the INDEX.

**Comment by landryb** [comment]
https://ftp.fr.openbsd.org/pub/sqlports should now work. I'm done beating this dead horse, if it works, fine, if not, then somebody else should pick up the ball.

**Comment by fingolfin** [comment]
@landryb wow, that was quick. Thank you very much for your efforts, and also thank you to @AMDmi3 for Repology!

**Comment by AMDmi3** [comment]
This is just superb, OpenBSD support is now near perfection (a pity though that this simple solution from the OpenBSD side had to linger for a year). I plan to additionally reduce number of [unmatched](https://repology.org/projects/?search=&maintainer=&category=&inrepo=openbsd&notinrepo=&repos=&families=1&repos_newest=&families_newest=) projects by around 200 stripping -flavors from package names.
