### ISSUE TITLE
Introduce problem types and improve problem formatting

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#196]
Instead of generating problem text from SQL just store problem type and some arguments.
~Handle problem types in config file, preferrably with template fragments to render them.~
We don't really need config here, it's enough to format them in a custom way in the template.

**Comment by davidak** [comment]
It would be useful to have the problem type in the API output, so it can get used to automatically fix problems.

For example this problem can easily get fixed by a script:

`"Homepage link \"http://kcat.strangesoft.net/alure.html\" is a permanent redirect to \"https://kcat.strangesoft.net/alure.html\" and should be updated"`

But this not. So it has to be a different type. Not only "homepage link broken", but "homepage 404".

`"Homepage link \"https://github.com/mulx/aacgain\" is dead (HTTP error 404) for more than a month."`

**Comment by AMDmi3** [comment]
> For example this problem can easily get fixed by a script

Not really. I've seen multiple cases where a homepage was overtaken and is now a domain for sale or an unrelated project. Unfortunately I've began to keep track of these just recently:

https://github.com/repology/repology/blob/master/domains-blacklist.yaml

So each problem is better to be processed manually.

**Comment by davidak** [comment]
@AMDmi3 of course you need review, but you could automate patch creation.
