### ISSUE TITLE
Ignore Gentoo packages with no metadata

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#939]
This affects Funtoo mainly, as it's quite common for package metadata to lag behind actual package versions there. This leads to metadata inconsistently unavailable for some packages, while it's crucial for splitting projects with conflicting names.

CC @danielrobbins @palica. Could the metadata (metadata/md5-cache/...) be updated for Funtoo? I have to deploy the fix (by ignoring packages) ASAP, after which affected packages will show up in parse [logs](https://repology.org/repositories/updates#funtoo_1.3). There are around 60 packages for Funtoo 1.3 and 260 for 1.4.

**Comment by danielrobbins** [comment]
Please give me a proper understanding of the problem, so I can help you fix it.

I do not understand what you mean by "it's quite common for package metadata to lag behind actual package versions." The metadata in Funtoo is from a Gentoo snapshot. It is *supposed* to "lag behind". And didn't we already deal with this issue of Funtoo results not having to impact Gentoo searches? So I don't understand how this is causing problems -- can you point me in the right direction in understanding this?

**Comment by AMDmi3** [comment]
Here's an example:

https://github.com/funtoo/gnome-kit/tree/3.32-prime/sys-apps/bolt → bolt-0.7
https://github.com/funtoo/gnome-kit/tree/3.32-prime/metadata/md5-cache/sys-apps → bolt-0.5

So we can't get DESCRIPTION and HOMEPAGE for bolt-0.7.

**Comment by AMDmi3** [comment]
Here are logs which show affected packages:

https://repology.org/log/1573565
https://repology.org/log/1573577

**Comment by danielrobbins** [comment]
OK, this is going to be kind of convoluted.

My understanding is that repology tracks distro packages. A site like http://gpo.zugaina.org/ tracks Gentoo overlays. And these overlays for the most part (probably 99.999% of them) have NO md5-cache at all. So if you were tracking overlays, you could not rely on ripping the data out of the md5-cache. The md5-cache was added as a speed-up mechanism (cache) for Portage to populate its local metadata cache quickly but it is not generally used for overlays.

Funtoo has several kits that are just basically overlays -- these are called the 'independently maintained kits' (listed here https://code.funtoo.org/bitbucket/projects/INDY). We have some md5-cache data still in the kits because these kits USED to be auto-generated. But generally, once independently-maintained, we don't auto-generate the metadata anymore. It might be nice if we did, but it's not at all needed. Portage doesn't need it.

So, all this to say that it's really a not a bug in funtoo that there is not updated md5-cache for some packages in our overlays.

Solutions:

1. This is more burdensome, but repology could spend some time adding the ability to extract metadata from ebuilds. I would understand if you consider this a pain in the butt and a lot of unnecessary work. Yet, without this, it is impossible to properly track overlays in the Gentoo ecosystem (maybe Funtoo is the only Gentoo-derived distro that uses overlays, and you don't care about overlays, which would make this a lot of work with very little gain for repology.)

2. I can add some code to our tree regeneration scripts so that instead of ignoring independently-maintained kits, our regen scripts will keep the md5-cache up-to-date on these repositories. This is really not a bad thing to do, though it really doesn't make a perceptible difference for Funtoo users so it's me basically doing this to make repology happy.

But really, this isn't a Funtoo bug, it's just a situation that is causing problems for repology. I could decide to completely remove md5-cache from our independently-maintained overlays if I wanted -- they don't need to exist. I probably won't, and will probably go with #2 option above some time relatively soon, but since this isn't an actual bug but a feature request, I am not going to rush a fix out tonight since nothing is broken on the Funtoo side.

**Comment by danielrobbins** [comment]
Another option I am thinking of is just to create a web service that you can query/download to get a complete set of metadata, so you don't have to parse the trees in the first place.

This is probably going to be the best solution. The reason is because we already have plans to do some things that are going to totally break repology in the future so rather than keep running into issues because we do things differently than Gentoo, it seems best to give the data to you in a stable, predictable format.

I will work on this, as I think it solves the problem going forward.

**Comment by AMDmi3** [comment]
> So if you were tracking overlays, you could not rely on ripping the data out of the md5-cache

Well Repology relies on two sources of metadata for Gentoo(ish) repositories - md5-cache and metadata.xml, homepage URLs can be extracted from both. We don't currently support many overlays, it's only Pentoo basically, and they are willing to fill metadata.xml in cases of conflicting names. Sabayon and calculated don't contain many packages so I've had no problems with these yet. Funtoo is currently the only one as large as Gentoo, thus providing many potential conflicts, but not supporting consistent md5-cache unlike the former.

> This is more burdensome, but repology could spend some time adding the ability to extract metadata from ebuilds. I would understand if you consider this a pain in the butt and a lot of unnecessary work.

In fact I've considered this an obvious and sane solution, however I've dropped this idea later as it would be impossible to implement. Parsing ebuilds (or PKGBUILDs or slackbuilds or BSD make code) basically implies running them which would be too slow (need to spawn shell a lot of times), insecure (need to run third party code) and/or complicated if you try to sandbox it, non-portable (as I'm currently running on FreeBSD, and shell based Linux build systems do not generally work in alien environment with different core utilities and filesystem hierarchy).

Alternative solution would be to reimplement a shell parser to parse shell code without running anything, but I don't think it's viable either *builds rely on the infrastructure and may use values retrieved from the system, which, again, cannot be done portably.

> I can add some code to our tree regeneration scripts so that instead of ignoring independently-maintained kits, our regen scripts will keep the md5-cache up-to-date on these repositories.

I've assumed this could be a short term solution, as it should be trivial since the repositories are still in Gentoo format and the code which updates metadata should work out of box. However I completely understand that this may be atavism not really useful for any other purposes, in which case it of course should be dropped and another solution sought as long as you're interested in Repology support.

> Another option I am thinking of is just to create a web service that you can query/download to get a complete set of metadata, so you don't have to parse the trees in the first place.

> This is probably going to be the best solution. The reason is because we already have plans to do some things that are going to totally break repology in the future so rather than keep running into issues because we do things differently than Gentoo, it seems best to give the data to you in a stable, predictable format.

Totally agree, this would be great, and that's all I'm basically asking for.
