### ISSUE TITLE
KISS git package source format

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-updater#993]
I noticed that Repology reported an error when parsing community (https://repology.org/log/1953818) which is most likely due to the git package support which recently landed in KISS.

The format is as follows for a git source.

```
# git+URL
git+https://github.com/dylanaraps/eiwd

# git+URL#hash
git+https://github.com/dylanaraps/eiwd#4a2d30bd1b053a9f1e4373d17c2ae6f3ccbc4148

# Some URLs also require '.git' (github is just an example)
git+https://github.com/dylanaraps/eiwd.git
```

I'm not sure if this is really an issue or not. Just opening it to inform you of the change and the simple format. :+1:

**Comment by AMDmi3** [comment]
But it's `git+git://`, is this even valid? It would not complain on `git://` or `git+https://`

**Comment by dylanaraps** [comment]
(`git+` is solely an identifier for the package manager and is stripped before given to `git clone`.)

You're right about it being weird and I will ask the maintainer to change it to `git+https://` which also works fine. If repology handles `git+http*` fine then I will close this as an issue on my end.

Apologies. :+1:

**Comment by AMDmi3** [comment]
While here, wanted to ask a thing: how are path (`xorg/intel-media-driver`) and package name (`intel-media-driver`) used in KISS? Does it make sense to refer to the former as "source package name" and the latter as "binary package name"? Which is better to show on the site (as in on e.g. https://repology.org/project/2bwm/versions)?

**Comment by dylanaraps** [comment]
They're loosely named categories in reality and `xorg` contains some packages which I'd like to move to `extra`.

Here's a rundown.

- `core`: The essential packages. What comes installed by default in every KISS system.
- `xorg`: Xorg packages or anything loosely related to the underneath of the graphical system.
    - This includes `mesa` and font related libraries as an example.
- `testing`: Packages undergoing testing. Typically used for new Firefox or Rust releases for example.
- `extra`: Any other packages which while not *required*, are essential in being in the official repositories (and not in community).
    - This includes things like Firefox, ffmpeg, various libraries etc.
- `community`: Everything else. 

I don't think displaying them as paths is the greatest idea though it's your call. This could work well if I cleaned up the Xorg repository a little, I'll work on this tomorrow. :+1:

**Comment by AMDmi3** [comment]
> I don't think displaying them as paths is the greatest idea though it's your call

Well I'm asking because I don't know KISS features. For instance, on FreeBSD we have the similar category/portname layout, however portnames are only unique within a category, and there are also package names unique globally which may be different from portnames, so it makes sense to refer to the both as source/binary package names (for instance, that'd would be `www/py-flask` and `py38-Flask` for flask). With this information it's possible to match Repology data with both port names and package names in both directions. The site should probably show both names, but for now the port name is shown for it's more useful for most people. I wanted to confirm that the same reasoning makes sense for KISS.

> This could work well if I cleaned up the Xorg repository a little, I'll work on this tomorrow

Good that you've mentioned it. In fact, I also need some package identifier to track its package history, and that identifier should be unique and as stable as possible (one of package names is used in most cases). My intention was to use category/portname, but if portnames are globally unique within a single repository it would be better to use them to make us tolerant to port moves across categories.

> Edit: Also, while we're talking: The community repository seems to show myself as the sole maintainer instead of the number of KISS users maintaining packages. https://repology.org/repository/kiss_community

Nice catch. The problem is likely caused by the fact that we use `--depth 1` for git checkouts to conserve space, so there's no history and the author is extracted from the latest commit. Will fix that.

**Comment by dylanaraps** [comment]
If there are any duplicates in a repository or subdirectory, this is an issue on my end. (There shouldn't be duplicates). Although, we may have `pkg` + `pkg-git` or `pkg` + `pkg-bin` as fairly rare examples.

To make it clearer, there are no duplicates between for example `core` and `xorg`. If there are, this is a bug. :+1:
